project_id = "sqbdqqbvxrmxnmrlqynu"

[functions.auto-complete-trips]
verify_jwt = false

[functions.analyze-receipt]
verify_jwt = false

[functions.concierge-agent]
verify_jwt = false

[functions.concierge-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false