// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqbdqqbvxrmxnmrlqynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxYmRxcWJ2eHJteG5tcmxxeW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjIzNDAsImV4cCI6MjA2OTc5ODM0MH0.FeZ0O1M2ZWF13oQ_rJjBN7yb3O4iHsDSfwr-7Upa3X0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});